# Generated by Django 5.2.4 on 2025-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
