# Generated by Django 5.2.4 on 2025-07-17 09:32

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_uploadedfile_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=uploader.models.upload_to_process_folder),
        ),
    ]
