# Generated by Django 5.2.4 on 2025-12-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Missing', 'Missing')], default='Missing', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_entries', to='uploader.uploadedfile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('process', 'date')},
            },
        ),
    ]
